package refresolve_test

// Parity net for chain parse-context-directive-intent-extension
// (docs/PARSE_CONTEXT.md §14.5). This is the GATE the T3 detection
// change and T4 surface wiring must pass: non-directive prompts stay
// classified exactly as they are today, and the non-directive handler
// envelope is unchanged (modulo volatile fields).
//
// Two frozen artifacts back this net (both hermetic — captured from a
// frozen corpus, NOT queried from the live grounding_events DB at test
// time):
//
//   - testdata/directive_intent_corpus_prompts.txt — the 125 distinct
//     real parse_context prompts (the grounded inventory, §14.1).
//   - testdata/directive_intent_corpus_parity.json — each prompt's
//     CURRENT DetectIntent shape (baseline), a partition tag, and (for
//     intentionally-changing entries) the target shape T3 will move it to.
//
// The golden JSON is regenerated by running this test with GEN_PARITY=1
// (see TestGenerateParityCorpus). The steady-state tests consume it.
//
// Partition semantics:
//   - must_not_change: the parity invariant. DetectIntent MUST return the
//     recorded baseline shape — forever. A mismatch here after T3/T4 is a
//     parity violation (a new pattern leaked onto a non-directive prompt).
//   - intentionally_changing: the execute/solve/review prompts T3 moves
//     from none → execute|fix|audit. Allowed to be EITHER baseline or
//     target across the T2→T3 transition (so this test stays green through
//     the change); T3 owns the "they actually moved to target" assertion.

import (
	"encoding/json"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"toolkit/internal/events"
	"toolkit/internal/refresolve"

	"context"
)

const (
	parityPromptsFile  = "testdata/directive_intent_corpus_prompts.txt"
	parityGoldenFile   = "testdata/directive_intent_corpus_parity.json"
	nonDirectiveGolden = "testdata/directive_intent_nondirective_envelopes.json"

	partitionMustNotChange = "must_not_change"
	partitionChanging      = "intentionally_changing"
)

// parityEntry is one frozen corpus prompt + its classification baseline.
type parityEntry struct {
	Text      string `json:"text"`
	Baseline  string `json:"baseline"`         // current DetectIntent shape
	Partition string `json:"partition"`        // must_not_change | intentionally_changing
	Target    string `json:"target,omitempty"` // shape T3 will move it to (intentionally_changing only)
}

// proposedExecute/Solve/Review mirror the T3 patterns (§14.3) ONLY for
// the generator's partition computation — they decide which currently-
// none prompts T3 is expected to reclassify. They are NOT the production
// detector; T3 lands that in intent_detect.go.
var (
	proposedExecute = regexp.MustCompile(`(?i)^(complete|work\s+(through|on)|pick\s+up|continue|resume|start|finish\s+(out|up)?|drive|carry\s+on|proceed\s+with)\b|(?i)\b(pick\s+up|work\s+through|continue\s+(work|working)|finish\s+(out|up))\b|(?i)\bplease\s+resume\b|(?i)^let'?s\s+(finish|revisit|wrap)\b|(?i)\bre-?resolve\b`)
	proposedSolve   = regexp.MustCompile(`(?i)^solve\b|(?i)\bsolve\s+(our|the|all)\b|(?i)\b(clear|empty|drain|clean\s+out)\s+(the\s+|our\s+)?(bug\s+)?backlog\b|(?i)\bempty\s+our\b`)
	proposedReview  = regexp.MustCompile(`(?i)^review\b|(?i)\btake a look\b|(?i)\blook through\b`)
	politeStripGen  = regexp.MustCompile(`(?i)^\s*(please\s+|could you\s+|can you\s+|i'?d like (you to\s+)?|would you\s+)`)
)

func loadParityCorpus(t *testing.T) []parityEntry {
	t.Helper()
	raw, err := os.ReadFile(parityGoldenFile)
	if err != nil {
		t.Fatalf("read parity golden (run GEN_PARITY=1 to generate): %v", err)
	}
	var entries []parityEntry
	if err := json.Unmarshal(raw, &entries); err != nil {
		t.Fatalf("parse parity golden: %v", err)
	}
	return entries
}

// TestGenerateParityCorpus regenerates the golden from the frozen prompt
// list. Run: GEN_PARITY=1 go test ./internal/refresolve -run TestGenerateParityCorpus
func TestGenerateParityCorpus(t *testing.T) {
	if os.Getenv("GEN_PARITY") == "" {
		t.Skip("set GEN_PARITY=1 to regenerate the parity golden")
	}
	raw, err := os.ReadFile(parityPromptsFile)
	if err != nil {
		t.Fatalf("read frozen prompts: %v", err)
	}
	var entries []parityEntry
	for _, line := range strings.Split(string(raw), "\n") {
		text := strings.TrimRight(line, "\r")
		if strings.TrimSpace(text) == "" {
			continue
		}
		baseline := string(refresolve.DetectIntent(text).Shape)
		e := parityEntry{Text: text, Baseline: baseline, Partition: partitionMustNotChange}
		if baseline == "none" {
			// Switch order MIRRORS production priority (intent_detect.go
			// ordered slice): fix > audit > execute. A currently-none
			// prompt matching multiple folds gets the higher-priority
			// shape — e.g. "take a look at the roadmap. pick up the next
			// task" matches both review(→audit) and execute, and
			// production yields audit because audit is checked first.
			stripped := politeStripGen.ReplaceAllString(strings.TrimSpace(text), "")
			switch {
			case proposedSolve.MatchString(stripped):
				e.Partition, e.Target = partitionChanging, "fix" // solve folds into fix
			case proposedReview.MatchString(stripped):
				e.Partition, e.Target = partitionChanging, "audit" // review folds into audit
			case proposedExecute.MatchString(stripped):
				e.Partition, e.Target = partitionChanging, "execute"
			}
		}
		entries = append(entries, e)
	}
	out, err := json.MarshalIndent(entries, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(parityGoldenFile, append(out, '\n'), 0o644); err != nil {
		t.Fatal(err)
	}
	// Report the partition breakdown so the generator run is auditable.
	counts := map[string]int{}
	targets := map[string]int{}
	for _, e := range entries {
		counts[e.Partition]++
		if e.Partition == partitionChanging {
			targets[e.Target]++
		}
	}
	t.Logf("generated %d entries: must_not_change=%d intentionally_changing=%d (targets: %v)",
		len(entries), counts[partitionMustNotChange], counts[partitionChanging], targets)
}

// TestParity_RealCorpusClassification is the permanent gate. For
// must_not_change entries the baseline shape is pinned forever; for
// intentionally_changing entries the shape may be baseline OR target
// (stable across the T2→T3 transition).
func TestParity_RealCorpusClassification(t *testing.T) {
	entries := loadParityCorpus(t)
	if len(entries) < 100 {
		t.Fatalf("parity corpus has only %d entries; expected the frozen ~125-prompt corpus", len(entries))
	}
	var mustCount, changeCount int
	for _, e := range entries {
		got := string(refresolve.DetectIntent(e.Text).Shape)
		switch e.Partition {
		case partitionMustNotChange:
			mustCount++
			if got != e.Baseline {
				t.Errorf("PARITY VIOLATION (must_not_change): DetectIntent(%q).Shape = %q, want %q\n  a new pattern leaked onto a non-directive prompt", e.Text, got, e.Baseline)
			}
		case partitionChanging:
			changeCount++
			if got != e.Baseline && got != e.Target {
				t.Errorf("intentionally_changing entry %q classified %q; want baseline=%q or target=%q", e.Text, got, e.Baseline, e.Target)
			}
		default:
			t.Errorf("entry %q has unknown partition %q", e.Text, e.Partition)
		}
	}
	t.Logf("parity corpus: %d must_not_change (pinned), %d intentionally_changing", mustCount, changeCount)
}

// TestDirectiveExtension_IntentionallyChangingMovesToTarget is the
// T3 "they actually moved" assertion (§14.5): every intentionally_
// changing corpus prompt must now classify as its recorded target
// shape (execute / fix-via-solve / audit-via-review) — not linger at
// none. This is the counterpart to the parity gate: parity proves we
// broke nothing; this proves the directive shapes actually fire.
func TestDirectiveExtension_IntentionallyChangingMovesToTarget(t *testing.T) {
	entries := loadParityCorpus(t)
	moved := map[string]int{}
	var stalled int
	for _, e := range entries {
		if e.Partition != partitionChanging {
			continue
		}
		got := string(refresolve.DetectIntent(e.Text).Shape)
		if got != e.Target {
			stalled++
			t.Errorf("directive prompt did not move to target: %q\n  got=%q want target=%q", e.Text, got, e.Target)
			continue
		}
		moved[e.Target]++
	}
	t.Logf("moved to target: %v (stalled=%d)", moved, stalled)
}

// --- non-directive envelope parity ---

// nonDirectivePrompts are token-free non-directive prompts: with an empty
// registry + empty DB their full envelope is deterministic, so the only
// volatile field is resolution_time_ms (normalized to 0 below). New
// firing intents / patterns must not leak any work-state or discipline
// ref onto these.
var nonDirectivePrompts = []string{
	"thanks",
	"ok cool",
	"that's a good point about the cache invalidation",
	"what does the fold hook do?",  // explain — docs-intent, no work-state
	"summarize the recent changes", // summarize — docs-intent, no work-state
}

func nonDirectiveEnvelope(t *testing.T, text string) string {
	t.Helper()
	registry := refresolve.NewRegistry()
	deps := refresolve.HandlerDeps{
		Project:          "mcp-servers",
		Registry:         registry,
		Cache:            refresolve.NewParseContextCache(),
		DriftFireTracker: refresolve.NewDriftFireTracker(),
		// No Pool, no WorkStateCache, no DisciplineFireTracker, no
		// KiwixSearcher: the non-directive path must produce a clean
		// envelope regardless.
		//
		// Hermetic drift state: a non-existent marker path + an empty proc
		// root make stdiodrift.Snapshot report DriftDetected=false, so the
		// stdio-drift candidate never surfaces. WITHOUT these overrides the
		// snapshot reads the live /proc + marker, so this parity net injects
		// a stdio-drift reference (and fails) on ANY dev box whose stdio
		// binary has drifted — i.e. after every commit, per the post-commit
		// advisor. Same hermetic-override pattern as drift_test.go.
		DriftMarkerPathOverride: filepath.Join(t.TempDir(), "no-marker"),
		DriftProcRootOverride:   t.TempDir(),
	}
	ctx := events.WithMCPSessionID(context.Background(), "parity-nondirective")
	body, _ := json.Marshal(struct {
		MessageText string `json:"message_text"`
	}{MessageText: text})
	r, err := refresolve.HandleParseContext(ctx, deps, body)
	if err != nil {
		t.Fatalf("HandleParseContext(%q): %v", text, err)
	}
	raw, err := json.Marshal(r)
	if err != nil {
		t.Fatal(err)
	}
	// Normalize volatile fields.
	var m map[string]any
	if err := json.Unmarshal(raw, &m); err != nil {
		t.Fatal(err)
	}
	delete(m, "resolution_time_ms")
	norm, _ := json.Marshal(m) // map marshal emits keys sorted — stable
	return string(norm)
}

// TestGenerateNonDirectiveEnvelopes regenerates the non-directive
// envelope golden. GEN_PARITY=1 go test -run TestGenerateNonDirectiveEnvelopes
func TestGenerateNonDirectiveEnvelopes(t *testing.T) {
	if os.Getenv("GEN_PARITY") == "" {
		t.Skip("set GEN_PARITY=1 to regenerate the non-directive envelope golden")
	}
	golden := map[string]string{}
	for _, p := range nonDirectivePrompts {
		golden[p] = nonDirectiveEnvelope(t, p)
	}
	out, _ := json.MarshalIndent(golden, "", "  ")
	if err := os.WriteFile(filepath.Join(nonDirectiveGolden), append(out, '\n'), 0o644); err != nil {
		t.Fatal(err)
	}
	t.Logf("generated %d non-directive envelope goldens", len(golden))
}

// TestParity_NonDirectiveEnvelopeUnchanged asserts the full handler
// envelope for non-directive prompts is byte-identical (modulo the
// normalized resolution_time_ms) to the frozen golden. Catches a new
// firing-intent or pattern leaking work-state/discipline refs onto a
// non-directive path.
func TestParity_NonDirectiveEnvelopeUnchanged(t *testing.T) {
	raw, err := os.ReadFile(nonDirectiveGolden)
	if err != nil {
		t.Fatalf("read non-directive golden (run GEN_PARITY=1): %v", err)
	}
	var golden map[string]string
	if err := json.Unmarshal(raw, &golden); err != nil {
		t.Fatal(err)
	}
	for _, p := range nonDirectivePrompts {
		want, ok := golden[p]
		if !ok {
			t.Errorf("golden missing prompt %q (regenerate)", p)
			continue
		}
		got := nonDirectiveEnvelope(t, p)
		if got != want {
			t.Errorf("PARITY VIOLATION: non-directive envelope changed for %q\n got:  %s\n want: %s", p, got, want)
		}
	}
}
