// One-shot backfill for bug 864 — events table missing 57 + 8 task
// terminal events + 2 chain terminal events. Two shapes:
//
//	Shape 1 (8 tasks + 2 chains): a terminal event EXISTS but its
//	UUIDv7 prefix encodes ~2002, so it sorts BEFORE the matching
//	TaskCreated/ChainCreated when ordered by event_id. The fold's
//	UPDATE-no-op swallows the synthetic; the row never reaches
//	terminal.
//
//	Shape 2 (57 tasks): NO terminal event exists at all.
//
// Both shapes resolve via the same mechanism: emit a fresh terminal
// event with a wall-clock UUIDv7 (generated by events.Emit itself).
// The fresh event sorts AFTER the TaskCreated/ChainCreated, so fold
// replay reaches the terminal state correctly. Existing buggy
// synthetic events stay (audit trail preserved).
package main

import (
	"context"
	"database/sql"
	"fmt"
	"log"
	"os"

	"toolkit/internal/db"
	"toolkit/internal/events"
	"toolkit/internal/projections"
)

const actorID = "migration-recovery-2026-05-22-gap-fill"

func main() {
	dbPath := os.Args[1]
	pool, err := db.Open(dbPath)
	if err != nil {
		log.Fatalf("open db: %v", err)
	}
	defer pool.Close()

	// Register the projection fold hook so the new events also
	// converge the projection rows in the same tx.
	events.SetFoldHook(func(ctx context.Context, tx *sql.Tx, evt events.RawEvent) error {
		return projections.FoldAll(ctx, tx, projections.RawEvent{
			EventID: evt.EventID, Ts: evt.Ts, ActorKind: evt.ActorKind, ActorID: evt.ActorID,
			Type: evt.Type, EntityKind: evt.EntityKind, EntitySlug: evt.EntitySlug,
			EntityProjectID: evt.EntityProjectID, Payload: evt.Payload, Rationale: evt.Rationale,
			CausedByEventID: evt.CausedByEventID, RelatedEntities: evt.RelatedEntities,
			SpanID: evt.SpanID, SchemaVersion: evt.SchemaVersion,
		})
	})

	ctx := events.WithActor(context.Background(), events.Actor{Kind: "system", ID: actorID})

	taskCount, err := backfillTasks(ctx, pool)
	if err != nil {
		log.Fatalf("backfill tasks: %v", err)
	}
	chainCount, err := backfillChains(ctx, pool)
	if err != nil {
		log.Fatalf("backfill chains: %v", err)
	}
	fmt.Printf("emitted %d task terminal events + %d chain terminal events\n", taskCount, chainCount)
}

func backfillTasks(ctx context.Context, pool *db.Pool) (int, error) {
	rows, err := pool.DB().QueryContext(ctx, `
		SELECT pct.slug, pct.status, COALESCE(pct.commit_sha, ''), pct.chain_id, pcs.project_id
		FROM proj_current_tasks pct
		LEFT JOIN proj_chain_status pcs ON pcs.id = pct.chain_id
		WHERE pct.status IN ('closed','cancelled')
		  AND (
		    NOT EXISTS (
		      SELECT 1 FROM events e WHERE e.entity_kind='task' AND e.entity_slug=pct.slug
		        AND e.type IN ('TaskCompleted','TaskCancelled','TaskRetired')
		    )
		    OR (
		      (SELECT MIN(event_id) FROM events e WHERE e.entity_kind='task' AND e.entity_slug=pct.slug AND e.type IN ('TaskCompleted','TaskCancelled','TaskRetired'))
		      < (SELECT MIN(event_id) FROM events e WHERE e.entity_kind='task' AND e.entity_slug=pct.slug AND e.type='TaskCreated')
		    )
		  )`)
	if err != nil {
		return 0, fmt.Errorf("query gap tasks: %w", err)
	}
	defer rows.Close()
	type gapTask struct {
		slug, status, commitSHA, projectID string
		chainID                            int64
	}
	var tasks []gapTask
	for rows.Next() {
		var t gapTask
		if err := rows.Scan(&t.slug, &t.status, &t.commitSHA, &t.chainID, &t.projectID); err != nil {
			return 0, err
		}
		tasks = append(tasks, t)
	}
	if err := rows.Err(); err != nil {
		return 0, err
	}

	rationale := "bug 864 gap-fill: emit terminal event with wall-clock UUIDv7 so fold replay reaches terminal status"
	for _, t := range tasks {
		if err := pool.WithWrite(ctx, func(tx *sql.Tx) error {
			var payload events.Payload
			if t.status == "closed" {
				sha := t.commitSHA
				if sha == "" {
					sha = "unversioned"
				}
				summary := "gap-fill: closed task missing wall-clock-UUIDv7 terminal event (bug 864)"
				payload = events.TaskCompletedPayload{CommitSHA: &sha, ClosureSummary: &summary}
			} else {
				reason := "gap-fill: cancelled task missing wall-clock-UUIDv7 terminal event (bug 864)"
				payload = events.TaskCancelledPayload{Reason: &reason}
			}
			projID := t.projectID
			_, emitErr := events.Emit(ctx, tx, events.EmitArgs{
				Entity: events.EntityRef{
					Kind:      "task",
					Slug:      t.slug,
					ProjectID: &projID,
				},
				Payload:   payload,
				Rationale: &rationale,
			})
			return emitErr
		}); err != nil {
			return 0, fmt.Errorf("emit for task %s: %w", t.slug, err)
		}
	}
	return len(tasks), nil
}

func backfillChains(ctx context.Context, pool *db.Pool) (int, error) {
	rows, err := pool.DB().QueryContext(ctx, `
		SELECT pcs.slug, pcs.project_id, COALESCE(pcs.closure_summary, '')
		FROM proj_chain_status pcs
		WHERE pcs.status='closed'
		  AND (
		    NOT EXISTS (
		      SELECT 1 FROM events e WHERE e.entity_kind='chain' AND e.entity_slug=pcs.slug AND e.type='ChainClosed'
		    )
		    OR (
		      (SELECT MIN(event_id) FROM events e WHERE e.entity_kind='chain' AND e.entity_slug=pcs.slug AND e.type='ChainClosed')
		      < (SELECT MIN(event_id) FROM events e WHERE e.entity_kind='chain' AND e.entity_slug=pcs.slug AND e.type='ChainCreated')
		    )
		  )`)
	if err != nil {
		return 0, fmt.Errorf("query gap chains: %w", err)
	}
	defer rows.Close()
	type gapChain struct{ slug, projectID, closureSummary string }
	var chains []gapChain
	for rows.Next() {
		var c gapChain
		if err := rows.Scan(&c.slug, &c.projectID, &c.closureSummary); err != nil {
			return 0, err
		}
		chains = append(chains, c)
	}
	if err := rows.Err(); err != nil {
		return 0, err
	}

	rationale := "bug 864 gap-fill: emit ChainClosed with wall-clock UUIDv7 so fold replay reaches status=closed"
	for _, c := range chains {
		if err := pool.WithWrite(ctx, func(tx *sql.Tx) error {
			summary := c.closureSummary
			if summary == "" {
				summary = "gap-fill: closed chain missing wall-clock-UUIDv7 ChainClosed event (bug 864)"
			}
			projID := c.projectID
			_, emitErr := events.Emit(ctx, tx, events.EmitArgs{
				Entity: events.EntityRef{
					Kind:      "chain",
					Slug:      c.slug,
					ProjectID: &projID,
				},
				Payload:   events.ChainClosedPayload{ClosureSummary: &summary},
				Rationale: &rationale,
			})
			return emitErr
		}); err != nil {
			return 0, fmt.Errorf("emit for chain %s: %w", c.slug, err)
		}
	}
	return len(chains), nil
}
